language: java
jdk:
    - openjdk15
addons:
    sonarcloud:
        organization: "unimibsoftengcourse2021"
        token: ${SONAR_TOKEN}
script:
- mvn clean install sonar:sonar -Pqa -Dsonar.projectKey=UnimibSoftEngCourse2021_progetto-risiko-1-gruppo-risiko-1
